/* tslint:disable */
/* eslint-disable */
/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/prompt-values-api';
export * from './api/countries-api';
export * from './api/home-contact-information-changes-api';
export * from './api/people-api';
export * from './api/phone-validation-api';
export * from './api/work-contact-information-changes-api';

