/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  PromptValuesApi,
  CountriesApi,
  HomeContactInformationChangesApi,
  PeopleApi,
  PhoneValidationApi,
  WorkContactInformationChangesApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { WorkdayPersonCustom } from "./client-custom";

export class WorkdayPerson extends WorkdayPersonCustom {
  readonly promptValues: PromptValuesApi;
  readonly countries: CountriesApi;
  readonly homeContactInformationChanges: HomeContactInformationChangesApi;
  readonly people: PeopleApi;
  readonly phoneValidation: PhoneValidationApi;
  readonly workContactInformationChanges: WorkContactInformationChangesApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.promptValues = new PromptValuesApi(configuration);
    this.countries = new CountriesApi(configuration);
    this.homeContactInformationChanges = new HomeContactInformationChangesApi(configuration);
    this.people = new PeopleApi(configuration);
    this.phoneValidation = new PhoneValidationApi(configuration);
    this.workContactInformationChanges = new WorkContactInformationChangesApi(configuration);
  }

}
