/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf
 */
export interface AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf
     */
    'descriptor'?: string;
}

