/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AboriginalIndigenousIdentification37580627f49d10002587d93d0a820000 } from './aboriginal-indigenous-identification37580627f49d10002587d93d0a820000';

/**
 * Returns the \\~aboriginal/indigenous identification\\~ for a person.
 * @export
 * @interface AboriginalIndigenousIdentification37580627f49d1000258f815dc9c00001
 */
export interface AboriginalIndigenousIdentification37580627f49d1000258f815dc9c00001 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof AboriginalIndigenousIdentification37580627f49d1000258f815dc9c00001
     */
    'descriptor'?: string;
}

