/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressReference9c3ab7b846e4100009e5ec55fa530024AllOf } from './address-reference9c3ab7b846e4100009e5ec55fa530024-all-of';
import { CountryA58f621b14ee1000146a3350196300e7 } from './country-a58f621b14ee1000146a3350196300e7';
import { CountryCityA58f621b14ee1000146a333da1c900e6 } from './country-city-a58f621b14ee1000146a333da1c900e6';
import { CountryRegionA58f621b14ee100014b01c1cbabe00f4 } from './country-region-a58f621b14ee100014b01c1cbabe00f4';
import { UsageA58f621b14ee100014b01c034eeb00f3 } from './usage-a58f621b14ee100014b01c034eeb00f3';

/**
 * 
 * @export
 * @interface AddressReference9c3ab7b846e4100009e5ec55fa530024
 */
export interface AddressReference9c3ab7b846e4100009e5ec55fa530024 {
    /**
     * Local Address Line 4 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine4Local'?: string;
    /**
     * City Subdivision 2 - Local for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'citySubdivision2Local'?: string;
    /**
     * Local Address Line 8 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine8Local'?: string;
    /**
     * City Subdivision 1 - Local for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'citySubdivision1Local'?: string;
    /**
     * Address Line 1 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine1'?: string;
    /**
     * Address Line 9 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine9'?: string;
    /**
     * Region Subdivision 1 - Local for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'regionSubdivision1Local'?: string;
    /**
     * Address Line 8 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine8'?: string;
    /**
     * Full Formatted Address
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'fullFormattedAddress'?: string;
    /**
     * Address Line 2 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine2'?: string;
    /**
     * Local Address Line 6 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine6Local'?: string;
    /**
     * Region Subdivision 2 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'regionSubdivision2'?: string;
    /**
     * 
     * @type {CountryCityA58f621b14ee1000146a333da1c900e6}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'countryCity'?: CountryCityA58f621b14ee1000146a333da1c900e6;
    /**
     * Address Line 4 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine4'?: string;
    /**
     * The postal code for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'postalCode'?: string;
    /**
     * Full Formatted Local Address
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'fullFormattedLocalAddress'?: string;
    /**
     * Local Address Line 1 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine1Local'?: string;
    /**
     * City Subdivision 1 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'citySubdivision1'?: string;
    /**
     * Address Line 6 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine6'?: string;
    /**
     * 
     * @type {UsageA58f621b14ee100014b01c034eeb00f3}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'usage'?: UsageA58f621b14ee100014b01c034eeb00f3;
    /**
     * City for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'city'?: string;
    /**
     * Address Line 3 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine3'?: string;
    /**
     * City Subdivision 2 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'citySubdivision2'?: string;
    /**
     * Local Address Line 9 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine9Local'?: string;
    /**
     * The Effective Date for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'effective'?: string;
    /**
     * Local Address Line 7 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine7Local'?: string;
    /**
     * Address Line 5 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine5'?: string;
    /**
     * Region Subdivision 1 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'regionSubdivision1'?: string;
    /**
     * City - Local for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'cityLocal'?: string;
    /**
     * Local Address Line 2 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine2Local'?: string;
    /**
     * 
     * @type {CountryRegionA58f621b14ee100014b01c1cbabe00f4}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'countryRegion'?: CountryRegionA58f621b14ee100014b01c1cbabe00f4;
    /**
     * Local Address Line 3 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine3Local'?: string;
    /**
     * 
     * @type {CountryA58f621b14ee1000146a3350196300e7}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'country'?: CountryA58f621b14ee1000146a3350196300e7;
    /**
     * Local Address Line 5 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine5Local'?: string;
    /**
     * Address Line 7 for the address.
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'addressLine7'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof AddressReference9c3ab7b846e4100009e5ec55fa530024
     */
    'id'?: string;
}

