/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The address reference instance from the Alternate Work Location (Primary Work Address) that links to the Work Contact Change event.
 * @export
 * @interface AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68
 */
export interface AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof AlternateWorkLocationBdfa2c83ea5e10002b70a80a153e5d68
     */
    'href'?: string;
}

