/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BloodType6de928ab1284100056beb6e9884101cd } from './blood-type6de928ab1284100056beb6e9884101cd';

/**
 * Returns the blood type for a person.
 * @export
 * @interface BloodTypeA63806bf8576100013fa9dcbb7dc0111
 */
export interface BloodTypeA63806bf8576100013fa9dcbb7dc0111 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof BloodTypeA63806bf8576100013fa9dcbb7dc0111
     */
    'descriptor'?: string;
}

