/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BloodType6de928ab1284100056beb6e9884101cdAllOf
 */
export interface BloodType6de928ab1284100056beb6e9884101cdAllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof BloodType6de928ab1284100056beb6e9884101cdAllOf
     */
    'descriptor'?: string;
}

