/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisabilityCertificationBasis15d8b82e323110000db825167ee603a9 } from './disability-certification-basis15d8b82e323110000db825167ee603a9';

/**
 * The Certification Basis for a \\~Disability\\~ status.
 * @export
 * @interface CertificationBasis6de928ab128410005c56a638b9d4024c
 */
export interface CertificationBasis6de928ab128410005c56a638b9d4024c {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CertificationBasis6de928ab128410005c56a638b9d4024c
     */
    'descriptor'?: string;
}

