/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessProcessParameters83f6f6b7c38d100009c7ad91dd414a16 } from './business-process-parameters83f6f6b7c38d100009c7ad91dd414a16';

/**
 * 
 * @export
 * @interface ChangeContactInformationEvent765b18aa13af1000064a10bf37b800edAllOf
 */
export interface ChangeContactInformationEvent765b18aa13af1000064a10bf37b800edAllOf {
    /**
     * 
     * @type {BusinessProcessParameters83f6f6b7c38d100009c7ad91dd414a16}
     * @memberof ChangeContactInformationEvent765b18aa13af1000064a10bf37b800edAllOf
     */
    'businessProcessParameters'?: BusinessProcessParameters83f6f6b7c38d100009c7ad91dd414a16;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ChangeContactInformationEvent765b18aa13af1000064a10bf37b800edAllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof ChangeContactInformationEvent765b18aa13af1000064a10bf37b800edAllOf
     */
    'id'?: string;
}

