/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CityAb827579ee1710002095f51c0e3f0178AllOf } from './city-ab827579ee1710002095f51c0e3f0178-all-of';

/**
 * 
 * @export
 * @interface CityAb827579ee1710002095f51c0e3f0178
 */
export interface CityAb827579ee1710002095f51c0e3f0178 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof CityAb827579ee1710002095f51c0e3f0178
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CityAb827579ee1710002095f51c0e3f0178
     */
    'descriptor'?: string;
}

