/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000AllOf
 */
export interface CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000AllOf
     */
    'id'?: string;
}

