/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Comments86093b8a932f10001499f356ff83012eAllOf } from './comments86093b8a932f10001499f356ff83012e-all-of';
import { Person86093b8a932f10001499f38c72410130 } from './person86093b8a932f10001499f38c72410130';

/**
 * 
 * @export
 * @interface Comments86093b8a932f10001499f356ff83012e
 */
export interface Comments86093b8a932f10001499f356ff83012e {
    /**
     * Gives the moment at which the instance was originally created.
     * @type {string}
     * @memberof Comments86093b8a932f10001499f356ff83012e
     */
    'commentDate'?: string;
    /**
     * Comment
     * @type {string}
     * @memberof Comments86093b8a932f10001499f356ff83012e
     */
    'comment'?: string;
    /**
     * 
     * @type {Person86093b8a932f10001499f38c72410130}
     * @memberof Comments86093b8a932f10001499f356ff83012e
     */
    'person'?: Person86093b8a932f10001499f38c72410130;
}

