/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * 
 * @export
 * @interface ComponentType98e46a86842a10000dc278233c7e0280
 */
export interface ComponentType98e46a86842a10000dc278233c7e0280 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof ComponentType98e46a86842a10000dc278233c7e0280
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof ComponentType98e46a86842a10000dc278233c7e0280
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof ComponentType98e46a86842a10000dc278233c7e0280
     */
    'href'?: string;
}

