/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * 
 * @export
 * @interface ComponentTypeEae9f0331ab51000162aafecb6bf00eb
 */
export interface ComponentTypeEae9f0331ab51000162aafecb6bf00eb {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof ComponentTypeEae9f0331ab51000162aafecb6bf00eb
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof ComponentTypeEae9f0331ab51000162aafecb6bf00eb
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof ComponentTypeEae9f0331ab51000162aafecb6bf00eb
     */
    'href'?: string;
}

