/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Content type of the attachment
 * @export
 * @interface ContentType6b9baf67ce60100011fd138066140090
 */
export interface ContentType6b9baf67ce60100011fd138066140090 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof ContentType6b9baf67ce60100011fd138066140090
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof ContentType6b9baf67ce60100011fd138066140090
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof ContentType6b9baf67ce60100011fd138066140090
     */
    'href'?: string;
}

