/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country8beeb162738910001433a1ef009a01d0 } from './country8beeb162738910001433a1ef009a01d0';

/**
 * \\~Country\\~
 * @export
 * @interface Country81f66ab16f7510005c53d8fd5f5b4852
 */
export interface Country81f66ab16f7510005c53d8fd5f5b4852 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Country81f66ab16f7510005c53d8fd5f5b4852
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof Country81f66ab16f7510005c53d8fd5f5b4852
     */
    'id'?: string;
}

