/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RegionAb827579ee1710001f7eb5159a9b0170 } from './region-ab827579ee1710001f7eb5159a9b0170';

/**
 * Country Region
 * @export
 * @interface CountryRegionA58f621b14ee100014b01c1cbabe00f4
 */
export interface CountryRegionA58f621b14ee100014b01c1cbabe00f4 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryRegionA58f621b14ee100014b01c1cbabe00f4
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryRegionA58f621b14ee100014b01c1cbabe00f4
     */
    'descriptor'?: string;
}

