/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country1089da0ab90910000f6d7bd30bb20881AllOf } from './country1089da0ab90910000f6d7bd30bb20881-all-of';

/**
 * 
 * @export
 * @interface Country1089da0ab90910000f6d7bd30bb20881
 */
export interface Country1089da0ab90910000f6d7bd30bb20881 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Country1089da0ab90910000f6d7bd30bb20881
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof Country1089da0ab90910000f6d7bd30bb20881
     */
    'id'?: string;
}

