/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Country8beeb162738910001433a1ef009a01d0AllOf
 */
export interface Country8beeb162738910001433a1ef009a01d0AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Country8beeb162738910001433a1ef009a01d0AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof Country8beeb162738910001433a1ef009a01d0AllOf
     */
    'id'?: string;
}

