/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country8beeb162738910001433a1ef009a01d0 } from './country8beeb162738910001433a1ef009a01d0';

/**
 * \\~Country\\~ Phone Code for \\~Country\\~
 * @export
 * @interface CountryAb827579ee1710001caa7c36228c0153
 */
export interface CountryAb827579ee1710001caa7c36228c0153 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryAb827579ee1710001caa7c36228c0153
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryAb827579ee1710001caa7c36228c0153
     */
    'id'?: string;
}

