/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country8beeb162738910001433a1ef009a01d0 } from './country8beeb162738910001433a1ef009a01d0';

/**
 * The \\~Country\\~ for the Military Status.
 * @export
 * @interface Country6de928ab128410005b9a894c5c67022a
 */
export interface Country6de928ab128410005b9a894c5c67022a {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Country6de928ab128410005b9a894c5c67022a
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof Country6de928ab128410005b9a894c5c67022a
     */
    'id'?: string;
}

