/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CountryAndNationality06544db2578d10000ec1cd4257350000AllOf
 */
export interface CountryAndNationality06544db2578d10000ec1cd4257350000AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryAndNationality06544db2578d10000ec1cd4257350000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryAndNationality06544db2578d10000ec1cd4257350000AllOf
     */
    'id'?: string;
}

