/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CityAb827579ee1710002095f51c0e3f0178 } from './city-ab827579ee1710002095f51c0e3f0178';

/**
 * \\~Country\\~ City
 * @export
 * @interface CountryCityC1bb9f46f65210002d2fa2bb24a300a1
 */
export interface CountryCityC1bb9f46f65210002d2fa2bb24a300a1 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryCityC1bb9f46f65210002d2fa2bb24a300a1
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryCityC1bb9f46f65210002d2fa2bb24a300a1
     */
    'descriptor'?: string;
}

