/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CountryPredefinedNameComponentAb5c028f50b310001b9916066f1f0250AllOf
 */
export interface CountryPredefinedNameComponentAb5c028f50b310001b9916066f1f0250AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryPredefinedNameComponentAb5c028f50b310001b9916066f1f0250AllOf
     */
    'descriptor'?: string;
}

