/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country1089da0ab90910000f6e4df524710885 } from './country1089da0ab90910000f6e4df524710885';

/**
 * 
 * @export
 * @interface CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
 */
export interface CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf {
    /**
     * The phone code for a country.
     * @type {string}
     * @memberof CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
     */
    'countryPhoneCode'?: string;
    /**
     * 
     * @type {Country1089da0ab90910000f6e4df524710885}
     * @memberof CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
     */
    'country'?: Country1089da0ab90910000f6e4df524710885;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
     */
    'id'?: string;
}

