/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RegionAb827579ee1710001f7eb5159a9b0170 } from './region-ab827579ee1710001f7eb5159a9b0170';

/**
 * Country Region
 * @export
 * @interface CountryRegion81f66ab16f7510005c53d8be2fe44847
 */
export interface CountryRegion81f66ab16f7510005c53d8be2fe44847 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryRegion81f66ab16f7510005c53d8be2fe44847
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryRegion81f66ab16f7510005c53d8be2fe44847
     */
    'descriptor'?: string;
}

