/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PersonLocalizedAddressComponentFormat98e46a86842a10000dc277ddefc7027b } from './person-localized-address-component-format98e46a86842a10000dc277ddefc7027b';

/**
 * 
 * @export
 * @interface CountriesGetAddressComponentsResponse
 */
export interface CountriesGetAddressComponentsResponse {
    /**
     * 
     * @type {Array<PersonLocalizedAddressComponentFormat98e46a86842a10000dc277ddefc7027b>}
     * @memberof CountriesGetAddressComponentsResponse
     */
    'data'?: Array<PersonLocalizedAddressComponentFormat98e46a86842a10000dc277ddefc7027b>;
    /**
     * 
     * @type {number}
     * @memberof CountriesGetAddressComponentsResponse
     */
    'total'?: number;
}

