/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country1089da0ab90910000f6e4df524710885 } from './country1089da0ab90910000f6e4df524710885';
import { CountryPhoneCode1089da0ab90910000f6e4de36f670883 } from './country-phone-code1089da0ab90910000f6e4de36f670883';

/**
 * Phone \\~country\\~
 * @export
 * @interface CountryPhoneCode1089da0ab90910000f7089365467088c
 */
export interface CountryPhoneCode1089da0ab90910000f7089365467088c {
    /**
     * The phone code for a country.
     * @type {string}
     * @memberof CountryPhoneCode1089da0ab90910000f7089365467088c
     */
    'countryPhoneCode'?: string;
    /**
     * 
     * @type {Country1089da0ab90910000f6e4df524710885}
     * @memberof CountryPhoneCode1089da0ab90910000f7089365467088c
     */
    'country'?: Country1089da0ab90910000f6e4df524710885;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryPhoneCode1089da0ab90910000f7089365467088c
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryPhoneCode1089da0ab90910000f7089365467088c
     */
    'id'?: string;
}

