/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Country1089da0ab90910000f6d7bd30bb20881AllOf
 */
export interface Country1089da0ab90910000f6d7bd30bb20881AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Country1089da0ab90910000f6d7bd30bb20881AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof Country1089da0ab90910000f6d7bd30bb20881AllOf
     */
    'id'?: string;
}

