/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PhoneDeviceType1089da0ab90910000f85ace9e4050892 } from './phone-device-type1089da0ab90910000f85ace9e4050892';

/**
 * Phone device type
 * @export
 * @interface DeviceType1089da0ab90910000f7089256c7b0888
 */
export interface DeviceType1089da0ab90910000f7089256c7b0888 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof DeviceType1089da0ab90910000f7089256c7b0888
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof DeviceType1089da0ab90910000f7089256c7b0888
     */
    'id'?: string;
}

