/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PhoneDeviceType33e26848dc00100062db00beab0c0205 } from './phone-device-type33e26848dc00100062db00beab0c0205';

/**
 * Phone device type
 * @export
 * @interface DeviceTypeA58f621b14ee100018ac4d72f02901ea
 */
export interface DeviceTypeA58f621b14ee100018ac4d72f02901ea {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof DeviceTypeA58f621b14ee100018ac4d72f02901ea
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof DeviceTypeA58f621b14ee100018ac4d72f02901ea
     */
    'id'?: string;
}

