/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Disability15d8b82e323110000d98d0fc4d9903a5 } from './disability15d8b82e323110000d98d0fc4d9903a5';

/**
 * The \\~Disability\\~ for a \\~Disability\\~ Status.
 * @export
 * @interface Disability6de928ab128410005c56a64ec69f024f
 */
export interface Disability6de928ab128410005c56a64ec69f024f {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Disability6de928ab128410005c56a64ec69f024f
     */
    'descriptor'?: string;
}

