/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Disability15d8b82e323110000d98d0fc4d9903a5AllOf } from './disability15d8b82e323110000d98d0fc4d9903a5-all-of';

/**
 * 
 * @export
 * @interface Disability15d8b82e323110000d98d0fc4d9903a5
 */
export interface Disability15d8b82e323110000d98d0fc4d9903a5 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Disability15d8b82e323110000d98d0fc4d9903a5
     */
    'descriptor'?: string;
}

