/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisabilityGrade15d8b82e323110000ddf3ff73d2e03aeAllOf } from './disability-grade15d8b82e323110000ddf3ff73d2e03ae-all-of';

/**
 * 
 * @export
 * @interface DisabilityGrade15d8b82e323110000ddf3ff73d2e03ae
 */
export interface DisabilityGrade15d8b82e323110000ddf3ff73d2e03ae {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof DisabilityGrade15d8b82e323110000ddf3ff73d2e03ae
     */
    'descriptor'?: string;
}

