/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CertificationBasis6de928ab128410005c56a638b9d4024c } from './certification-basis6de928ab128410005c56a638b9d4024c';
import { Disability6de928ab128410005c56a64ec69f024f } from './disability6de928ab128410005c56a64ec69f024f';
import { Grade6de928ab128410005c56a5feed2e0244 } from './grade6de928ab128410005c56a5feed2e0244';
import { WorkerDocument15d8b82e323110000e0117c92d9803b2 } from './worker-document15d8b82e323110000e0117c92d9803b2';

/**
 * 
 * @export
 * @interface DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
 */
export interface DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf {
    /**
     * 
     * @type {Disability6de928ab128410005c56a64ec69f024f}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'disability'?: Disability6de928ab128410005c56a64ec69f024f;
    /**
     * 
     * @type {CertificationBasis6de928ab128410005c56a638b9d4024c}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'certificationBasis'?: CertificationBasis6de928ab128410005c56a638b9d4024c;
    /**
     * The Certification ID for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'certificationID'?: string;
    /**
     * 
     * @type {Grade6de928ab128410005c56a5feed2e0244}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'grade'?: Grade6de928ab128410005c56a5feed2e0244;
    /**
     * The Rehabilitation Provided for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'rehabilitationProvided'?: string;
    /**
     * The Accommodations Requested for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'accommodationRequested'?: string;
    /**
     * The Work Restrictions for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'workRestrictions'?: string;
    /**
     * The \\~Disability\\~ Authority for a \\~Disability\\~ Status
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'certifiedBy'?: string;
    /**
     * The \\~Disability\\~ Status Date for a \\~Disability\\~ Status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'statusDate'?: string;
    /**
     * The Degree for a \\~Disability\\~ status.
     * @type {number}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'degreePercent'?: number;
    /**
     * The Date Known for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'knownDate'?: string;
    /**
     * The End Date for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'endDate'?: string;
    /**
     * The Accommodations Provided for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'accommodationProvided'?: string;
    /**
     * The Certification Location for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'certifiedAt'?: string;
    /**
     * The Severity Recognition Date for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'severityRecognitionDate'?: string;
    /**
     * The Worker Documents for this Disability Status.
     * @type {Array<WorkerDocument15d8b82e323110000e0117c92d9803b2>}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'workerDocuments'?: Array<WorkerDocument15d8b82e323110000e0117c92d9803b2>;
    /**
     * The Note for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'note'?: string;
    /**
     * The Remaining Capacity for a \\~Disability\\~ status.
     * @type {number}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'remainingCapacity'?: number;
    /**
     * The reference id for the \\~disability\\~ status.  This is the unique identifier for the \\~disability\\~ status that is assigned at creation and then maintained throughout its life as it is edited.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'statusID'?: string;
    /**
     * The FTE Toward Quota for a \\~Disability\\~ status.
     * @type {number}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'fteTowardQuota'?: number;
    /**
     * The Rehabilitation Requested for a \\~Disability\\~ status.
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'rehabilitationRequested'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof DisabilityStatus6de928ab128410005c56a5a5299c0239AllOf
     */
    'descriptor'?: string;
}

