/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Usage6333dee5ac2010000c8653405aaa0038 } from './usage6333dee5ac2010000c8653405aaa0038';

/**
 * 
 * @export
 * @interface EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
 */
export interface EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf {
    /**
     * The email address.
     * @type {string}
     * @memberof EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
     */
    'emailAddress'?: string;
    /**
     * 
     * @type {Usage6333dee5ac2010000c8653405aaa0038}
     * @memberof EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
     */
    'usage'?: Usage6333dee5ac2010000c8653405aaa0038;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
     */
    'id'?: string;
}

