/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ERRORMODELREFERENCE
 */
export interface ERRORMODELREFERENCE {
    /**
     * A description of the error
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'error': string;
    /**
     * The code that corresponds to the error message. Use the error code to drive programmatic error-handling behavior. Don\'t use error message strings for this purpose because they are subject to change
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'code'?: string;
    /**
     * The field related to the error
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'field'?: string;
    /**
     * The path of the field related to the error
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'path'?: string;
}

