/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Location6de928ab128410005960a25f7ff401e5 } from './location6de928ab128410005960a25f7ff401e5';

/**
 * 
 * @export
 * @interface Ethnicity6de928ab1284100058892e53dac501d1AllOf
 */
export interface Ethnicity6de928ab1284100058892e53dac501d1AllOf {
    /**
     * 
     * @type {Location6de928ab128410005960a25f7ff401e5}
     * @memberof Ethnicity6de928ab1284100058892e53dac501d1AllOf
     */
    'location'?: Location6de928ab128410005960a25f7ff401e5;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Ethnicity6de928ab1284100058892e53dac501d1AllOf
     */
    'descriptor'?: string;
}

