/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700ae } from './ethnicities-for-visual-survey-ebff7995b021100014bbd5c6cff700ae';
import { Ethnicity6de928ab1284100058892e53dac501d1 } from './ethnicity6de928ab1284100058892e53dac501d1';

/**
 * Current Person
 * @export
 * @interface EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104
 */
export interface EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104 {
    /**
     * True if the person is indicated as Hispanic or Latino for visual survey.
     * @type {boolean}
     * @memberof EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104
     */
    'hispanicOrLatinoForVisualSurvey'?: boolean;
    /**
     * The ethnicities indicated on the person\'s visual survey.
     * @type {Array<Ethnicity6de928ab1284100058892e53dac501d1>}
     * @memberof EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104
     */
    'ethnicities'?: Array<Ethnicity6de928ab1284100058892e53dac501d1>;
}

