/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FACETSMODELREFERENCEInnerValuesInner
 */
export interface FACETSMODELREFERENCEInnerValuesInner {
    /**
     * The number of instances returned by this facet
     * @type {number}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'count'?: number;
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'id': string;
    /**
     * A description of the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'href'?: string;
}

