/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FACETSMODELREFERENCEInnerValuesInner } from './facetsmodelreferenceinner-values-inner';

/**
 * This object represents the possible facets for this resource
 * @export
 * @interface FACETSMODELREFERENCEInner
 */
export interface FACETSMODELREFERENCEInner {
    /**
     * A description of the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInner
     */
    'descriptor'?: string;
    /**
     * The alias used to select the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInner
     */
    'facetParameter'?: string;
    /**
     * the facet values
     * @type {Array<FACETSMODELREFERENCEInnerValuesInner>}
     * @memberof FACETSMODELREFERENCEInner
     */
    'values'?: Array<FACETSMODELREFERENCEInnerValuesInner>;
}

