/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Gender6de928ab12841000544f9cd350c201b9AllOf } from './gender6de928ab12841000544f9cd350c201b9-all-of';

/**
 * 
 * @export
 * @interface Gender6de928ab12841000544f9cd350c201b9
 */
export interface Gender6de928ab12841000544f9cd350c201b9 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Gender6de928ab12841000544f9cd350c201b9
     */
    'descriptor'?: string;
}

