/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisabilityGrade15d8b82e323110000ddf3ff73d2e03ae } from './disability-grade15d8b82e323110000ddf3ff73d2e03ae';

/**
 * The Grade for a \\~Disability\\~ status.
 * @export
 * @interface Grade6de928ab128410005c56a5feed2e0244
 */
export interface Grade6de928ab128410005c56a5feed2e0244 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Grade6de928ab128410005c56a5feed2e0244
     */
    'descriptor'?: string;
}

