/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryPredefinedNameComponentAb5c028f50b310001b9916066f1f0250 } from './country-predefined-name-component-ab5c028f50b310001b9916066f1f0250';

/**
 * Returns the hereditary suffix from the name.
 * @export
 * @interface Hereditary11c67b72c9c610000edf72cf8506004d
 */
export interface Hereditary11c67b72c9c610000edf72cf8506004d {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Hereditary11c67b72c9c610000edf72cf8506004d
     */
    'descriptor'?: string;
}

