/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InstantMessengerTypeE3f4243ada0b10000d441b1688d20087AllOf
 */
export interface InstantMessengerTypeE3f4243ada0b10000d441b1688d20087AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof InstantMessengerTypeE3f4243ada0b10000d441b1688d20087AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof InstantMessengerTypeE3f4243ada0b10000d441b1688d20087AllOf
     */
    'id'?: string;
}

