/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TypeDe08a6c876a810000cb2e3dd8853001a } from './type-de08a6c876a810000cb2e3dd8853001a';
import { UsageDe08a6c876a810000cb2e3d738be0019 } from './usage-de08a6c876a810000cb2e3d738be0019';

/**
 * 
 * @export
 * @interface InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016AllOf
 */
export interface InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016AllOf {
    /**
     * 
     * @type {TypeDe08a6c876a810000cb2e3dd8853001a}
     * @memberof InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016AllOf
     */
    'type'?: TypeDe08a6c876a810000cb2e3dd8853001a;
    /**
     * The instant messenger account username.
     * @type {string}
     * @memberof InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016AllOf
     */
    'userName'?: string;
    /**
     * 
     * @type {UsageDe08a6c876a810000cb2e3d738be0019}
     * @memberof InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016AllOf
     */
    'usage'?: UsageDe08a6c876a810000cb2e3d738be0019;
    /**
     * Id of the instance
     * @type {string}
     * @memberof InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016AllOf
     */
    'id'?: string;
}

