/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface INSTANCEMODELREFERENCE
 */
export interface INSTANCEMODELREFERENCE {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof INSTANCEMODELREFERENCE
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof INSTANCEMODELREFERENCE
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof INSTANCEMODELREFERENCE
     */
    'href'?: string;
}

