/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LgbtIdentification6de928ab128410005a65d120bc8c020aAllOf } from './lgbt-identification6de928ab128410005a65d120bc8c020a-all-of';

/**
 * 
 * @export
 * @interface LgbtIdentification6de928ab128410005a65d120bc8c020a
 */
export interface LgbtIdentification6de928ab128410005a65d120bc8c020a {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof LgbtIdentification6de928ab128410005a65d120bc8c020a
     */
    'descriptor'?: string;
}

