/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocationAaeb64c958b2100011f0c7fc94120224AllOf } from './location-aaeb64c958b2100011f0c7fc94120224-all-of';

/**
 * 
 * @export
 * @interface LocationAaeb64c958b2100011f0c7fc94120224
 */
export interface LocationAaeb64c958b2100011f0c7fc94120224 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof LocationAaeb64c958b2100011f0c7fc94120224
     */
    'descriptor'?: string;
}

