/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocationAaeb64c958b2100011f0c7fc94120224 } from './location-aaeb64c958b2100011f0c7fc94120224';

/**
 * The location context of the Social Benefits Locality
 * @export
 * @interface Location80df32d43a5810000d59f391b32400d8
 */
export interface Location80df32d43a5810000d59f391b32400d8 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Location80df32d43a5810000d59f391b32400d8
     */
    'descriptor'?: string;
}

