/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MaritalStatusInformation6de928ab1284100059f5dc52629b01f4 } from './marital-status-information6de928ab1284100059f5dc52629b01f4';
import { Status6de928ab1284100059f5dc66f77e01f6 } from './status6de928ab1284100059f5dc66f77e01f6';

/**
 * Current Person
 * @export
 * @interface MaritalStatus6de928ab1284100059f67714875a01f8
 */
export interface MaritalStatus6de928ab1284100059f67714875a01f8 {
    /**
     * The Marital Status Date for a person.
     * @type {string}
     * @memberof MaritalStatus6de928ab1284100059f67714875a01f8
     */
    'date'?: string;
    /**
     * 
     * @type {Status6de928ab1284100059f5dc66f77e01f6}
     * @memberof MaritalStatus6de928ab1284100059f67714875a01f8
     */
    'status'?: Status6de928ab1284100059f5dc66f77e01f6;
}

