/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
 */
export interface MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf {
    /**
     * Filename
     * @type {string}
     * @memberof MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
     */
    'filename'?: string;
    /**
     * Person ID
     * @type {string}
     * @memberof MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
     */
    'person_id'?: string;
    /**
     * Media ID
     * @type {string}
     * @memberof MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
     */
    'media_id'?: string;
    /**
     * Download Link
     * @type {string}
     * @memberof MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
     */
    'download_audio'?: string;
}

