/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000AllOf } from './military-discharge-type-b15af3935f8910001f7585a44c0b0000-all-of';

/**
 * 
 * @export
 * @interface MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000
 */
export interface MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000
     */
    'id'?: string;
}

