/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000 } from './military-discharge-type-reference-b26f12db214d100010f22b23c4e70000';
import { MilitaryServiceReference6de928ab128410005b41e4b2f27d021e } from './military-service-reference6de928ab128410005b41e4b2f27d021e';
import { Rank6de928ab128410005b41e4ba56a6021f } from './rank6de928ab128410005b41e4ba56a6021f';
import { Status6de928ab128410005b41e4a4e4d2021c } from './status6de928ab128410005b41e4a4e4d2021c';
import { Type6de928ab128410005b41e4ac0ec5021d } from './type6de928ab128410005b41e4ac0ec5021d';

/**
 * 
 * @export
 * @interface MilitaryService6de928ab128410005b41e47e6d890218AllOf
 */
export interface MilitaryService6de928ab128410005b41e47e6d890218AllOf {
    /**
     * 
     * @type {MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'militaryDischargeTypeReference'?: MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000;
    /**
     * Notes associated with the Military Service.
     * @type {string}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'notes'?: string;
    /**
     * The Discharge Date for the Military Service.
     * @type {string}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'discharge'?: string;
    /**
     * 
     * @type {Rank6de928ab128410005b41e4ba56a6021f}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'rank'?: Rank6de928ab128410005b41e4ba56a6021f;
    /**
     * 
     * @type {Status6de928ab128410005b41e4a4e4d2021c}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'status'?: Status6de928ab128410005b41e4a4e4d2021c;
    /**
     * 
     * @type {MilitaryServiceReference6de928ab128410005b41e4b2f27d021e}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'militaryServiceReference'?: MilitaryServiceReference6de928ab128410005b41e4b2f27d021e;
    /**
     * The Military Status Begin Date for the Military Service.
     * @type {string}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'begin'?: string;
    /**
     * 
     * @type {Type6de928ab128410005b41e4ac0ec5021d}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'type'?: Type6de928ab128410005b41e4ac0ec5021d;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MilitaryService6de928ab128410005b41e47e6d890218AllOf
     */
    'descriptor'?: string;
}

