/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MilitaryRank6de928ab128410005be5dbfb939d0234AllOf
 */
export interface MilitaryRank6de928ab128410005be5dbfb939d0234AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MilitaryRank6de928ab128410005be5dbfb939d0234AllOf
     */
    'descriptor'?: string;
}

