/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246AllOf
 */
export interface MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246AllOf
     */
    'descriptor'?: string;
}

