/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MilitaryServiceType6de928ab128410005bc12d1bc69b0230AllOf
 */
export interface MilitaryServiceType6de928ab128410005bc12d1bc69b0230AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MilitaryServiceType6de928ab128410005bc12d1bc69b0230AllOf
     */
    'descriptor'?: string;
}

