/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MilitaryDischargeTypeB15af3935f8910001f7585a44c0b0000 } from './military-discharge-type-b15af3935f8910001f7585a44c0b0000';

/**
 * The \\~Military Discharge Type\\~ reference.
 * @export
 * @interface MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000
 */
export interface MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof MilitaryDischargeTypeReferenceB26f12db214d100010f22b23c4e70000
     */
    'id'?: string;
}

