/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246AllOf } from './military-service-reference-aaeb64c958b2100016889fe0267e0246-all-of';

/**
 * 
 * @export
 * @interface MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246
 */
export interface MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof MilitaryServiceReferenceAaeb64c958b2100016889fe0267e0246
     */
    'descriptor'?: string;
}

