/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * 
 * @export
 * @interface MULTIPLEINSTANCEMODELREFERENCE
 */
export interface MULTIPLEINSTANCEMODELREFERENCE {
    /**
     * 
     * @type {number}
     * @memberof MULTIPLEINSTANCEMODELREFERENCE
     */
    'total'?: number;
    /**
     * 
     * @type {Array<INSTANCEMODELREFERENCE>}
     * @memberof MULTIPLEINSTANCEMODELREFERENCE
     */
    'data'?: Array<INSTANCEMODELREFERENCE>;
}

