/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country33e26848dc0010002f1ae802adc30074 } from './country33e26848dc0010002f1ae802adc30074';
import { Hereditary11c67b72c9c610000edf72cf8506004d } from './hereditary11c67b72c9c610000edf72cf8506004d';
import { Salutation11c67b72c9c610000edf7291ae7b004c } from './salutation11c67b72c9c610000edf7291ae7b004c';
import { Social11c67b72c9c610000edf72e003d1004e } from './social11c67b72c9c610000edf72e003d1004e';
import { Title11c67b72c9c610000edf72f0b3c5004f } from './title11c67b72c9c610000edf72f0b3c5004f';

/**
 * 
 * @export
 * @interface Name33e26848dc0010002f1ae76d63ec0061AllOf
 */
export interface Name33e26848dc0010002f1ae76d63ec0061AllOf {
    /**
     * 
     * @type {Title11c67b72c9c610000edf72f0b3c5004f}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'title'?: Title11c67b72c9c610000edf72f0b3c5004f;
    /**
     * The person\'s secondary family name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'secondaryLocal'?: string;
    /**
     * The secondary family name for a person.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'secondaryLast'?: string;
    /**
     * 
     * @type {Salutation11c67b72c9c610000edf7291ae7b004c}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'salutation'?: Salutation11c67b72c9c610000edf7291ae7b004c;
    /**
     * The person\'s family name.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'primary'?: string;
    /**
     * The person\'s last name in second local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'primaryLocal2'?: string;
    /**
     * The person\'s tertiary last name.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'tertiaryLast'?: string;
    /**
     * The Full Name for a person, when it is provided. Workday only tracks Full Name for countries where the Full Name name component is used.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'full'?: string;
    /**
     * 
     * @type {Social11c67b72c9c610000edf72e003d1004e}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'social'?: Social11c67b72c9c610000edf72e003d1004e;
    /**
     * The person\'s given name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'firstLocal'?: string;
    /**
     * The first or given name for a person.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'first'?: string;
    /**
     * 
     * @type {Hereditary11c67b72c9c610000edf72cf8506004d}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'hereditary'?: Hereditary11c67b72c9c610000edf72cf8506004d;
    /**
     * The person\'s middle name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'middleLocal'?: string;
    /**
     * The person\'s given name in second local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'firstLocal2'?: string;
    /**
     * The person\'s last name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'primaryLocal'?: string;
    /**
     * 
     * @type {Country33e26848dc0010002f1ae802adc30074}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'country'?: Country33e26848dc0010002f1ae802adc30074;
    /**
     * The middle name from the name.
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'middle'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof Name33e26848dc0010002f1ae76d63ec0061AllOf
     */
    'id'?: string;
}

