/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns the Top Level (overall) Business Process that this Event is part of or returns the same instance if this Event is not a sub-process.
 * @export
 * @interface OverallBusinessProcess5d688bd57bb910001815ab49927724aa
 */
export interface OverallBusinessProcess5d688bd57bb910001815ab49927724aa {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof OverallBusinessProcess5d688bd57bb910001815ab49927724aa
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof OverallBusinessProcess5d688bd57bb910001815ab49927724aa
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof OverallBusinessProcess5d688bd57bb910001815ab49927724aa
     */
    'href'?: string;
}

