/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InstantMessengerAccount33e26848dc00100036f723337ebb0132 } from './instant-messenger-account33e26848dc00100036f723337ebb0132';

/**
 * 
 * @export
 * @interface PeopleGetHomeInstantMessengersResponse
 */
export interface PeopleGetHomeInstantMessengersResponse {
    /**
     * 
     * @type {Array<InstantMessengerAccount33e26848dc00100036f723337ebb0132>}
     * @memberof PeopleGetHomeInstantMessengersResponse
     */
    'data'?: Array<InstantMessengerAccount33e26848dc00100036f723337ebb0132>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetHomeInstantMessengersResponse
     */
    'total'?: number;
}

