/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmailReference9c3ab7b846e41000327e788d9664012a } from './email-reference9c3ab7b846e41000327e788d9664012a';

/**
 * 
 * @export
 * @interface PeopleGetWorkEmailsResponse
 */
export interface PeopleGetWorkEmailsResponse {
    /**
     * 
     * @type {Array<EmailReference9c3ab7b846e41000327e788d9664012a>}
     * @memberof PeopleGetWorkEmailsResponse
     */
    'data'?: Array<EmailReference9c3ab7b846e41000327e788d9664012a>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetWorkEmailsResponse
     */
    'total'?: number;
}

