/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Name33e26848dc0010002f1ae76d63ec0061 } from './name33e26848dc0010002f1ae76d63ec0061';

/**
 * 
 * @export
 * @interface PeopleGetPreferredNameResponse
 */
export interface PeopleGetPreferredNameResponse {
    /**
     * 
     * @type {Array<Name33e26848dc0010002f1ae76d63ec0061>}
     * @memberof PeopleGetPreferredNameResponse
     */
    'data'?: Array<Name33e26848dc0010002f1ae76d63ec0061>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetPreferredNameResponse
     */
    'total'?: number;
}

