/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PhoneReferenceDf014bc8b5fa10000af0fe7cb0ab00dd } from './phone-reference-df014bc8b5fa10000af0fe7cb0ab00dd';

/**
 * 
 * @export
 * @interface PeopleGetHomePhonesResponse
 */
export interface PeopleGetHomePhonesResponse {
    /**
     * 
     * @type {Array<PhoneReferenceDf014bc8b5fa10000af0fe7cb0ab00dd>}
     * @memberof PeopleGetHomePhonesResponse
     */
    'data'?: Array<PhoneReferenceDf014bc8b5fa10000af0fe7cb0ab00dd>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetHomePhonesResponse
     */
    'total'?: number;
}

