/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebAddress33e26848dc0010003893a0202ced0165 } from './web-address33e26848dc0010003893a0202ced0165';

/**
 * 
 * @export
 * @interface PeopleGetHomeWebAddressesResponse
 */
export interface PeopleGetHomeWebAddressesResponse {
    /**
     * 
     * @type {Array<WebAddress33e26848dc0010003893a0202ced0165>}
     * @memberof PeopleGetHomeWebAddressesResponse
     */
    'data'?: Array<WebAddress33e26848dc0010003893a0202ced0165>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetHomeWebAddressesResponse
     */
    'total'?: number;
}

