/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PersonPublicRepresentationD8f2aecf3d63100016a77ab413a20235 } from './person-public-representation-d8f2aecf3d63100016a77ab413a20235';

/**
 * 
 * @export
 * @interface PeopleGetPublicContactInformationResponse
 */
export interface PeopleGetPublicContactInformationResponse {
    /**
     * 
     * @type {Array<PersonPublicRepresentationD8f2aecf3d63100016a77ab413a20235>}
     * @memberof PeopleGetPublicContactInformationResponse
     */
    'data'?: Array<PersonPublicRepresentationD8f2aecf3d63100016a77ab413a20235>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetPublicContactInformationResponse
     */
    'total'?: number;
}

