/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MediaDownload5d5f0fb1184b10000b16f0e5c20f0000 } from './media-download5d5f0fb1184b10000b16f0e5c20f0000';

/**
 * 
 * @export
 * @interface PeopleGetNamePronunciationsResponse
 */
export interface PeopleGetNamePronunciationsResponse {
    /**
     * 
     * @type {Array<MediaDownload5d5f0fb1184b10000b16f0e5c20f0000>}
     * @memberof PeopleGetNamePronunciationsResponse
     */
    'data'?: Array<MediaDownload5d5f0fb1184b10000b16f0e5c20f0000>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetNamePronunciationsResponse
     */
    'total'?: number;
}

