/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PersonPhoto6b9baf67ce60100007d43c79e7a30011 } from './person-photo6b9baf67ce60100007d43c79e7a30011';

/**
 * 
 * @export
 * @interface PeopleGetPersonalPhotosResponse
 */
export interface PeopleGetPersonalPhotosResponse {
    /**
     * 
     * @type {Array<PersonPhoto6b9baf67ce60100007d43c79e7a30011>}
     * @memberof PeopleGetPersonalPhotosResponse
     */
    'data'?: Array<PersonPhoto6b9baf67ce60100007d43c79e7a30011>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetPersonalPhotosResponse
     */
    'total'?: number;
}

