/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressReference9c3ab7b846e4100009e5ec55fa530024 } from './address-reference9c3ab7b846e4100009e5ec55fa530024';

/**
 * 
 * @export
 * @interface PeopleGetHomeAddressesResponse
 */
export interface PeopleGetHomeAddressesResponse {
    /**
     * 
     * @type {Array<AddressReference9c3ab7b846e4100009e5ec55fa530024>}
     * @memberof PeopleGetHomeAddressesResponse
     */
    'data'?: Array<AddressReference9c3ab7b846e4100009e5ec55fa530024>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetHomeAddressesResponse
     */
    'total'?: number;
}

