/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PersonalInformation414c4cee7d91100023fe329d6f900018 } from './personal-information414c4cee7d91100023fe329d6f900018';

/**
 * 
 * @export
 * @interface PeopleGetPersonalInfoResponse
 */
export interface PeopleGetPersonalInfoResponse {
    /**
     * 
     * @type {Array<PersonalInformation414c4cee7d91100023fe329d6f900018>}
     * @memberof PeopleGetPersonalInfoResponse
     */
    'data'?: Array<PersonalInformation414c4cee7d91100023fe329d6f900018>;
    /**
     * 
     * @type {number}
     * @memberof PeopleGetPersonalInfoResponse
     */
    'total'?: number;
}

