/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UniversalIDE451ce2c8b48100007c31392a1ff00c2 } from './universal-ide451ce2c8b48100007c31392a1ff00c2';

/**
 * 
 * @export
 * @interface PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
 */
export interface PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf {
    /**
     * The image for the person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'photos'?: string;
    /**
     * The home email addresses for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'homeEmails'?: string;
    /**
     * The person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'personalInformation'?: string;
    /**
     * The home web addresses for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'homeWebAddresses'?: string;
    /**
     * 
     * @type {UniversalIDE451ce2c8b48100007c31392a1ff00c2}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'universal_ID'?: UniversalIDE451ce2c8b48100007c31392a1ff00c2;
    /**
     * The work instant messenger accounts for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'workInstantMessengers'?: string;
    /**
     * The home phone numbers for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'homePhones'?: string;
    /**
     * The preferred name for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'preferredName'?: string;
    /**
     * The work email addresses for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'workEmails'?: string;
    /**
     * The work addresses for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'workAddresses'?: string;
    /**
     * The work web addresses for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'workWebAddresses'?: string;
    /**
     * The home addresses for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'homeAddresses'?: string;
    /**
     * The Legal Name for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'legalName'?: string;
    /**
     * The Media related to Audio Name Pronunciation for a Person
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'audioNamePronunciation'?: string;
    /**
     * The social network accounts for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'socialNetworks'?: string;
    /**
     * The work phone numbers for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'workPhones'?: string;
    /**
     * The additional names for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'additionalNames'?: string;
    /**
     * The home instant messenger accounts for a person.
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'homeInstantMessengers'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'href'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PersonRepresentationE451ce2c8b48100007c312f3f72700b3AllOf
     */
    'id'?: string;
}

