/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000 } from './aboriginal-indigenous-details37580627f49d1000257d05e999ea0000';
import { AboriginalIndigenousIdentification37580627f49d1000258f815dc9c00001 } from './aboriginal-indigenous-identification37580627f49d1000258f815dc9c00001';
import { ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000 } from './active-military-uniformed-service9503dc49ae9610001fa8f76ed67d0000';
import { BloodTypeA63806bf8576100013fa9dcbb7dc0111 } from './blood-type-a63806bf8576100013fa9dcbb7dc0111';
import { CitizenshipStatus80df32d43a5810000f452a84da970114 } from './citizenship-status80df32d43a5810000f452a84da970114';
import { CountryAndNationality06544db2578d10000ec1cd4257350000 } from './country-and-nationality06544db2578d10000ec1cd4257350000';
import { DisabilityStatus6de928ab128410005c56a5a5299c0239 } from './disability-status6de928ab128410005c56a5a5299c0239';
import { EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104 } from './ethnicities-for-visual-survey2b5dded3d48e10001154aae4890a0104';
import { Ethnicity6de928ab1284100058892e53dac501d1 } from './ethnicity6de928ab1284100058892e53dac501d1';
import { Gender414c4cee7d91100023fe32ce16e70019 } from './gender414c4cee7d91100023fe32ce16e70019';
import { LgbtIdentification6de928ab128410005a65d120bc8c020a } from './lgbt-identification6de928ab128410005a65d120bc8c020a';
import { MaritalStatus6de928ab1284100059f67714875a01f8 } from './marital-status6de928ab1284100059f67714875a01f8';
import { MedicalExam2b5dded3d48e10001612959d7eb30169 } from './medical-exam2b5dded3d48e10001612959d7eb30169';
import { MilitaryService6de928ab128410005b41e47e6d890218 } from './military-service6de928ab128410005b41e47e6d890218';
import { PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5 } from './place-of-birth6de928ab1284100054a0b7e99c2b01c5';
import { PoliticalAffiliationBf9cd1638e0f10000a6604bfef01014a } from './political-affiliation-bf9cd1638e0f10000a6604bfef01014a';
import { PrimaryNationality2b5dded3d48e100013b87a5e15b3012a } from './primary-nationality2b5dded3d48e100013b87a5e15b3012a';
import { RelativeNamesE08d883b5eae10000403d79fe6d202e3 } from './relative-names-e08d883b5eae10000403d79fe6d202e3';
import { Religion6de928ab128410005a7df872e147020e } from './religion6de928ab128410005a7df872e147020e';
import { SelectiveServiceRegistrationCa34e5d6a47710000f902f4d90240000 } from './selective-service-registration-ca34e5d6a47710000f902f4d90240000';
import { SocialBenefitsLocality80df32d43a5810000ce182cac97500bf } from './social-benefits-locality80df32d43a5810000ce182cac97500bf';
import { UniformServiceReserveStatus9503dc49ae9610001e48857455610000 } from './uniform-service-reserve-status9503dc49ae9610001e48857455610000';
import { VeteransPreference898f4bc8578c100010cc072a1b140000 } from './veterans-preference898f4bc8578c100010cc072a1b140000';
import { VeteransPreferenceForRIFA04210f7e84510001fb2873228810000 } from './veterans-preference-for-rifa04210f7e84510001fb2873228810000';

/**
 * 
 * @export
 * @interface PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
 */
export interface PersonalInformation414c4cee7d91100023fe329d6f900018AllOf {
    /**
     * The Military Service for a person.
     * @type {Array<MilitaryService6de928ab128410005b41e47e6d890218>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'militaryServices'?: Array<MilitaryService6de928ab128410005b41e47e6d890218>;
    /**
     * The countries of additional nationality for a person.
     * @type {Array<CountryAndNationality06544db2578d10000ec1cd4257350000>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'additionalNationalities'?: Array<CountryAndNationality06544db2578d10000ec1cd4257350000>;
    /**
     * 
     * @type {MaritalStatus6de928ab1284100059f67714875a01f8}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'maritalStatus'?: MaritalStatus6de928ab1284100059f67714875a01f8;
    /**
     * 
     * @type {MedicalExam2b5dded3d48e10001612959d7eb30169}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'medicalExam'?: MedicalExam2b5dded3d48e10001612959d7eb30169;
    /**
     * The relative names for a person.
     * @type {Array<RelativeNamesE08d883b5eae10000403d79fe6d202e3>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'relativeNames'?: Array<RelativeNamesE08d883b5eae10000403d79fe6d202e3>;
    /**
     * 
     * @type {UniformServiceReserveStatus9503dc49ae9610001e48857455610000}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'uniformServiceReserveStatus'?: UniformServiceReserveStatus9503dc49ae9610001e48857455610000;
    /**
     * 
     * @type {ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'activeMilitaryUniformedService'?: ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000;
    /**
     * The Veteran\'s Preference Effective Date
     * @type {string}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'disabledVeteranLeaveDate'?: string;
    /**
     * True if the person has indicated they are Hispanic or Latino.
     * @type {boolean}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'hispanicOrLatino'?: boolean;
    /**
     * 
     * @type {PoliticalAffiliationBf9cd1638e0f10000a6604bfef01014a}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'politicalAffiliation'?: PoliticalAffiliationBf9cd1638e0f10000a6604bfef01014a;
    /**
     * The date of death for a person.
     * @type {string}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'dateOfDeath'?: string;
    /**
     * The Disability Statuses for a person.
     * @type {Array<DisabilityStatus6de928ab128410005c56a5a5299c0239>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'disabilityStatuses'?: Array<DisabilityStatus6de928ab128410005c56a5a5299c0239>;
    /**
     * The Religion for a person.
     * @type {Array<Religion6de928ab128410005a7df872e147020e>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'religion'?: Array<Religion6de928ab128410005a7df872e147020e>;
    /**
     * 
     * @type {AboriginalIndigenousIdentification37580627f49d1000258f815dc9c00001}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'aboriginalIndigenousIdentification'?: AboriginalIndigenousIdentification37580627f49d1000258f815dc9c00001;
    /**
     * Returns the \\~aboriginal/indigenous identification\\~ details for a person.
     * @type {Array<AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'aboriginalIndigenousIdentificationDetails'?: Array<AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000>;
    /**
     * 
     * @type {SocialBenefitsLocality80df32d43a5810000ce182cac97500bf}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'socialBenefitsLocality'?: SocialBenefitsLocality80df32d43a5810000ce182cac97500bf;
    /**
     * 
     * @type {PrimaryNationality2b5dded3d48e100013b87a5e15b3012a}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'primaryNationality'?: PrimaryNationality2b5dded3d48e100013b87a5e15b3012a;
    /**
     * 
     * @type {VeteransPreferenceForRIFA04210f7e84510001fb2873228810000}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'veteransPreferenceForRIF'?: VeteransPreferenceForRIFA04210f7e84510001fb2873228810000;
    /**
     * 
     * @type {Gender414c4cee7d91100023fe32ce16e70019}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'gender'?: Gender414c4cee7d91100023fe32ce16e70019;
    /**
     * 
     * @type {SelectiveServiceRegistrationCa34e5d6a47710000f902f4d90240000}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'selectiveServiceRegistration'?: SelectiveServiceRegistrationCa34e5d6a47710000f902f4d90240000;
    /**
     * The date of birth for a person.
     * @type {string}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'dateOfBirth'?: string;
    /**
     * Contains the veteran\'s preference for a person.
     * @type {Array<VeteransPreference898f4bc8578c100010cc072a1b140000>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'veteransPreference'?: Array<VeteransPreference898f4bc8578c100010cc072a1b140000>;
    /**
     * 
     * @type {PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'placeOfBirth'?: PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5;
    /**
     * The Ethnicity for a person.
     * @type {Array<Ethnicity6de928ab1284100058892e53dac501d1>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'ethnicities'?: Array<Ethnicity6de928ab1284100058892e53dac501d1>;
    /**
     * The Sexual Orientation & Gender Identity for a person.
     * @type {Array<LgbtIdentification6de928ab128410005a65d120bc8c020a>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'sexualOrientationAndGenderIdentity'?: Array<LgbtIdentification6de928ab128410005a65d120bc8c020a>;
    /**
     * 
     * @type {EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'ethnicitiesForVisualSurvey'?: EthnicitiesForVisualSurvey2b5dded3d48e10001154aae4890a0104;
    /**
     * The Citizenship Statuses for a person.
     * @type {Array<CitizenshipStatus80df32d43a5810000f452a84da970114>}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'citizenshipStatuses'?: Array<CitizenshipStatus80df32d43a5810000f452a84da970114>;
    /**
     * 
     * @type {BloodTypeA63806bf8576100013fa9dcbb7dc0111}
     * @memberof PersonalInformation414c4cee7d91100023fe329d6f900018AllOf
     */
    'bloodType'?: BloodTypeA63806bf8576100013fa9dcbb7dc0111;
}

