/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002aAllOf } from './person-country-view-definition-f206795ea40e1000040cc6f5da4f002a-all-of';

/**
 * 
 * @export
 * @interface PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a
 */
export interface PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a {
    /**
     * True if the country is enabled for Address Lookup.
     * @type {boolean}
     * @memberof PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a
     */
    'enabledForAddressLookup'?: boolean;
    /**
     * The ISO alpha-2 code for a country.
     * @type {string}
     * @memberof PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a
     */
    'alpha2Code'?: string;
    /**
     * The ISO alpha-3 code for a country.
     * @type {string}
     * @memberof PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a
     */
    'alpha3Code'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a
     */
    'href'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PersonCountryViewDefinitionF206795ea40e1000040cc6f5da4f002a
     */
    'id'?: string;
}

