/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContentType6b9baf67ce60100011fd138066140090 } from './content-type6b9baf67ce60100011fd138066140090';
import { PersonPhoto6b9baf67ce60100007d43c79e7a30011AllOf } from './person-photo6b9baf67ce60100007d43c79e7a30011-all-of';

/**
 * 
 * @export
 * @interface PersonPhoto6b9baf67ce60100007d43c79e7a30011
 */
export interface PersonPhoto6b9baf67ce60100007d43c79e7a30011 {
    /**
     * Width of Cropped Image.
     * @type {number}
     * @memberof PersonPhoto6b9baf67ce60100007d43c79e7a30011
     */
    'width'?: number;
    /**
     * 
     * @type {ContentType6b9baf67ce60100011fd138066140090}
     * @memberof PersonPhoto6b9baf67ce60100007d43c79e7a30011
     */
    'contentType'?: ContentType6b9baf67ce60100011fd138066140090;
    /**
     * File length of the image attachment.
     * @type {number}
     * @memberof PersonPhoto6b9baf67ce60100007d43c79e7a30011
     */
    'fileLength'?: number;
    /**
     * Height of Cropped Image.
     * @type {number}
     * @memberof PersonPhoto6b9baf67ce60100007d43c79e7a30011
     */
    'height'?: number;
    /**
     * Filename of the image attachment.
     * @type {string}
     * @memberof PersonPhoto6b9baf67ce60100007d43c79e7a30011
     */
    'fileName'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof PersonPhoto6b9baf67ce60100007d43c79e7a30011
     */
    'href'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PersonPhoto6b9baf67ce60100007d43c79e7a30011
     */
    'id'?: string;
}

