/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ComponentTypeEae9f0331ab51000162aafecb6bf00eb } from './component-type-eae9f0331ab51000162aafecb6bf00eb';

/**
 * 
 * @export
 * @interface PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
 */
export interface PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf {
    /**
     * 
     * @type {string}
     * @memberof PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
     */
    'type'?: string;
    /**
     * 
     * @type {ComponentTypeEae9f0331ab51000162aafecb6bf00eb}
     * @memberof PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
     */
    'componentType'?: ComponentTypeEae9f0331ab51000162aafecb6bf00eb;
    /**
     * The order assigned to the name component on the Maintain Name Components by Country task. The order of a name component is specific to a country.
     * @type {string}
     * @memberof PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
     */
    'order'?: string;
    /**
     * The custom Web Service Alias defined on a name component. For use with the Recruiting API.
     * @type {string}
     * @memberof PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
     */
    'webServiceAlias'?: string;
    /**
     * The country-specific label override for a name component. If no country-specific override exists, the generic name component name is used. For example, for Russia, the label Patronymic Name overrides the underlying generic component name Secondary.
     * @type {string}
     * @memberof PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
     */
    'label'?: string;
    /**
     * True if the name component is display only on preferred. This field is for China only.
     * @type {boolean}
     * @memberof PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
     */
    'showDisplayOnlyOnPreferred'?: boolean;
    /**
     * True if the name component is required for the country.
     * @type {boolean}
     * @memberof PersonLocalizedNameComponentFormat51f9e585eec710001050c68b768b00eaAllOf
     */
    'required'?: boolean;
}

