/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Comment made by Person
 * @export
 * @interface Person86093b8a932f10001499f38c72410130
 */
export interface Person86093b8a932f10001499f38c72410130 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Person86093b8a932f10001499f38c72410130
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Person86093b8a932f10001499f38c72410130
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Person86093b8a932f10001499f38c72410130
     */
    'href'?: string;
}

