/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PhoneDeviceType33e26848dc00100062db00beab0c0205AllOf } from './phone-device-type33e26848dc00100062db00beab0c0205-all-of';

/**
 * 
 * @export
 * @interface PhoneDeviceType33e26848dc00100062db00beab0c0205
 */
export interface PhoneDeviceType33e26848dc00100062db00beab0c0205 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PhoneDeviceType33e26848dc00100062db00beab0c0205
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PhoneDeviceType33e26848dc00100062db00beab0c0205
     */
    'id'?: string;
}

