/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryPhoneCode1089da0ab90910000f7089365467088c } from './country-phone-code1089da0ab90910000f7089365467088c';
import { DeviceType1089da0ab90910000f7089256c7b0888 } from './device-type1089da0ab90910000f7089256c7b0888';
import { Usage1089da0ab90910000f70892f2de3088a } from './usage1089da0ab90910000f70892f2de3088a';

/**
 * 
 * @export
 * @interface PhoneReference1089da0ab90910000f70891a998b0887AllOf
 */
export interface PhoneReference1089da0ab90910000f70891a998b0887AllOf {
    /**
     * The phone extension.
     * @type {string}
     * @memberof PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    'extension'?: string;
    /**
     * The complete phone number.
     * @type {string}
     * @memberof PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    'completePhoneNumber'?: string;
    /**
     * 
     * @type {CountryPhoneCode1089da0ab90910000f7089365467088c}
     * @memberof PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    'countryPhoneCode'?: CountryPhoneCode1089da0ab90910000f7089365467088c;
    /**
     * 
     * @type {DeviceType1089da0ab90910000f7089256c7b0888}
     * @memberof PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    'deviceType'?: DeviceType1089da0ab90910000f7089256c7b0888;
    /**
     * 
     * @type {Usage1089da0ab90910000f70892f2de3088a}
     * @memberof PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    'usage'?: Usage1089da0ab90910000f70892f2de3088a;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    'id'?: string;
}

