/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PhoneDeviceType1089da0ab90910000f85ace9e4050892AllOf
 */
export interface PhoneDeviceType1089da0ab90910000f85ace9e4050892AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PhoneDeviceType1089da0ab90910000f85ace9e4050892AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PhoneDeviceType1089da0ab90910000f85ace9e4050892AllOf
     */
    'id'?: string;
}

