/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PoliticalAffiliation6de928ab128410005b04f3329eee0214AllOf } from './political-affiliation6de928ab128410005b04f3329eee0214-all-of';

/**
 * 
 * @export
 * @interface PoliticalAffiliation6de928ab128410005b04f3329eee0214
 */
export interface PoliticalAffiliation6de928ab128410005b04f3329eee0214 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PoliticalAffiliation6de928ab128410005b04f3329eee0214
     */
    'descriptor'?: string;
}

