/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryAndNationality06544db2578d10000ec1cd4257350000 } from './country-and-nationality06544db2578d10000ec1cd4257350000';

/**
 * Return\'s a person\'s nationality.
 * @export
 * @interface PrimaryNationality2b5dded3d48e100013b87a5e15b3012a
 */
export interface PrimaryNationality2b5dded3d48e100013b87a5e15b3012a {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PrimaryNationality2b5dded3d48e100013b87a5e15b3012a
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PrimaryNationality2b5dded3d48e100013b87a5e15b3012a
     */
    'id'?: string;
}

