/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MilitaryRank6de928ab128410005be5dbfb939d0234 } from './military-rank6de928ab128410005be5dbfb939d0234';

/**
 * Military Rank for Military Service
 * @export
 * @interface Rank6de928ab128410005b41e4ba56a6021f
 */
export interface Rank6de928ab128410005b41e4ba56a6021f {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Rank6de928ab128410005b41e4ba56a6021f
     */
    'descriptor'?: string;
}

