/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RegionAb827579ee1710001f7eb5159a9b0170AllOf
 */
export interface RegionAb827579ee1710001f7eb5159a9b0170AllOf {
    /**
     * Id of the instance
     * @type {string}
     * @memberof RegionAb827579ee1710001f7eb5159a9b0170AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RegionAb827579ee1710001f7eb5159a9b0170AllOf
     */
    'descriptor'?: string;
}

