/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RegionAb827579ee1710001f7eb5159a9b0170 } from './region-ab827579ee1710001f7eb5159a9b0170';

/**
 * Returns the Region of Birth for a person.
 * @export
 * @interface Region6de928ab12841000549fe6375a9301c2
 */
export interface Region6de928ab12841000549fe6375a9301c2 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof Region6de928ab12841000549fe6375a9301c2
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Region6de928ab12841000549fe6375a9301c2
     */
    'descriptor'?: string;
}

