/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AcademicSuffixE08d883b5eae10000403d7c0735402e9 } from './academic-suffix-e08d883b5eae10000403d7c0735402e9';
import { CountryE08d883b5eae10000403d7c8e60502eb } from './country-e08d883b5eae10000403d7c8e60502eb';
import { HereditarySuffixE08d883b5eae10000403d7efe24b02f3 } from './hereditary-suffix-e08d883b5eae10000403d7efe24b02f3';
import { HonorarySuffixE08d883b5eae10000403d7acba9602e5 } from './honorary-suffix-e08d883b5eae10000403d7acba9602e5';
import { LocalPersonNameE08d883b5eae10000403d7cd713c02ec } from './local-person-name-e08d883b5eae10000403d7cd713c02ec';
import { ProfessionalSuffixE08d883b5eae10000403d7e2171f02f0 } from './professional-suffix-e08d883b5eae10000403d7e2171f02f0';
import { RelativeNamesE08d883b5eae10000403d79fe6d202e3AllOf } from './relative-names-e08d883b5eae10000403d79fe6d202e3-all-of';
import { RelativeTypeE08d883b5eae1000040cc1231a5902f5 } from './relative-type-e08d883b5eae1000040cc1231a5902f5';
import { ReligiousSuffixE08d883b5eae10000403d7eb401e02f2 } from './religious-suffix-e08d883b5eae10000403d7eb401e02f2';
import { RoyalSuffixE08d883b5eae10000403d7d259db02ed } from './royal-suffix-e08d883b5eae10000403d7d259db02ed';
import { SalutationSuffixE08d883b5eae10000403d7d736c102ee } from './salutation-suffix-e08d883b5eae10000403d7d736c102ee';
import { SocialSuffixE08d883b5eae10000403d7dc081502ef } from './social-suffix-e08d883b5eae10000403d7dc081502ef';
import { TitleE08d883b5eae10000403d7b62abb02e7 } from './title-e08d883b5eae10000403d7b62abb02e7';

/**
 * 
 * @export
 * @interface RelativeNamesE08d883b5eae10000403d79fe6d202e3
 */
export interface RelativeNamesE08d883b5eae10000403d79fe6d202e3 {
    /**
     * 
     * @type {TitleE08d883b5eae10000403d7b62abb02e7}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'title'?: TitleE08d883b5eae10000403d7b62abb02e7;
    /**
     * The middle name for a relative name.
     * @type {string}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'middleName'?: string;
    /**
     * 
     * @type {RoyalSuffixE08d883b5eae10000403d7d259db02ed}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'royalSuffix'?: RoyalSuffixE08d883b5eae10000403d7d259db02ed;
    /**
     * 
     * @type {ReligiousSuffixE08d883b5eae10000403d7eb401e02f2}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'religiousSuffix'?: ReligiousSuffixE08d883b5eae10000403d7eb401e02f2;
    /**
     * 
     * @type {LocalPersonNameE08d883b5eae10000403d7cd713c02ec}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'localPersonName'?: LocalPersonNameE08d883b5eae10000403d7cd713c02ec;
    /**
     * The family name for a relative name.
     * @type {string}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'lastName'?: string;
    /**
     * The first or given name for a relative name.
     * @type {string}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'firstName'?: string;
    /**
     * 
     * @type {HonorarySuffixE08d883b5eae10000403d7acba9602e5}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'honorarySuffix'?: HonorarySuffixE08d883b5eae10000403d7acba9602e5;
    /**
     * 
     * @type {CountryE08d883b5eae10000403d7c8e60502eb}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'country'?: CountryE08d883b5eae10000403d7c8e60502eb;
    /**
     * The secondary family name for a relative name
     * @type {string}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'secondaryLastName'?: string;
    /**
     * 
     * @type {SalutationSuffixE08d883b5eae10000403d7d736c102ee}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'salutationSuffix'?: SalutationSuffixE08d883b5eae10000403d7d736c102ee;
    /**
     * 
     * @type {RelativeTypeE08d883b5eae1000040cc1231a5902f5}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'relativeType'?: RelativeTypeE08d883b5eae1000040cc1231a5902f5;
    /**
     * 
     * @type {SocialSuffixE08d883b5eae10000403d7dc081502ef}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'socialSuffix'?: SocialSuffixE08d883b5eae10000403d7dc081502ef;
    /**
     * 
     * @type {ProfessionalSuffixE08d883b5eae10000403d7e2171f02f0}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'professionalSuffix'?: ProfessionalSuffixE08d883b5eae10000403d7e2171f02f0;
    /**
     * The Full Name for a relative name, where provided. Workday only tracks Full Name for countries where the Full Name name component is used.
     * @type {string}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'fullName'?: string;
    /**
     * 
     * @type {AcademicSuffixE08d883b5eae10000403d7c0735402e9}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'academicSuffix'?: AcademicSuffixE08d883b5eae10000403d7c0735402e9;
    /**
     * 
     * @type {HereditarySuffixE08d883b5eae10000403d7efe24b02f3}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'hereditarySuffix'?: HereditarySuffixE08d883b5eae10000403d7efe24b02f3;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    'descriptor'?: string;
}

