/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RelativeTypeE08d883b5eae100003cff859e1ec02dd } from './relative-type-e08d883b5eae100003cff859e1ec02dd';

/**
 * Returns the relative type for a relative name
 * @export
 * @interface RelativeTypeE08d883b5eae1000040cc1231a5902f5
 */
export interface RelativeTypeE08d883b5eae1000040cc1231a5902f5 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RelativeTypeE08d883b5eae1000040cc1231a5902f5
     */
    'descriptor'?: string;
}

