/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Religion6de928ab128410005a7df872e147020eAllOf } from './religion6de928ab128410005a7df872e147020e-all-of';

/**
 * 
 * @export
 * @interface Religion6de928ab128410005a7df872e147020e
 */
export interface Religion6de928ab128410005a7df872e147020e {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Religion6de928ab128410005a7df872e147020e
     */
    'descriptor'?: string;
}

