/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Religion6de928ab128410005a7df872e147020eAllOf
 */
export interface Religion6de928ab128410005a7df872e147020eAllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Religion6de928ab128410005a7df872e147020eAllOf
     */
    'descriptor'?: string;
}

