/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country6de928ab128410005b9a894c5c67022a } from './country6de928ab128410005b9a894c5c67022a';
import { MilitaryStatus6de928ab128410005b9a8926efa80226 } from './military-status6de928ab128410005b9a8926efa80226';

/**
 * The Military Status for the Military Service.
 * @export
 * @interface Status6de928ab128410005b41e4a4e4d2021c
 */
export interface Status6de928ab128410005b41e4a4e4d2021c {
    /**
     * The military status description.
     * @type {string}
     * @memberof Status6de928ab128410005b41e4a4e4d2021c
     */
    'description'?: string;
    /**
     * 
     * @type {Country6de928ab128410005b9a894c5c67022a}
     * @memberof Status6de928ab128410005b41e4a4e4d2021c
     */
    'country'?: Country6de928ab128410005b9a894c5c67022a;
    /**
     * The military status code.
     * @type {string}
     * @memberof Status6de928ab128410005b41e4a4e4d2021c
     */
    'code'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Status6de928ab128410005b41e4a4e4d2021c
     */
    'descriptor'?: string;
}

