/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Location6de928ab1284100059cd755321a501f1 } from './location6de928ab1284100059cd755321a501f1';
import { MaritalStatus6de928ab1284100059b4fc2c983801e9 } from './marital-status6de928ab1284100059b4fc2c983801e9';

/**
 * Returns the Marital Status for a person.
 * @export
 * @interface Status6de928ab1284100059f5dc66f77e01f6
 */
export interface Status6de928ab1284100059f5dc66f77e01f6 {
    /**
     * 
     * @type {Location6de928ab1284100059cd755321a501f1}
     * @memberof Status6de928ab1284100059f5dc66f77e01f6
     */
    'location'?: Location6de928ab1284100059cd755321a501f1;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Status6de928ab1284100059f5dc66f77e01f6
     */
    'descriptor'?: string;
}

