/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryPredefinedNameComponentAb5c028f50b310001b9916066f1f0250 } from './country-predefined-name-component-ab5c028f50b310001b9916066f1f0250';

/**
 * Returns the prefix from the name.
 * @export
 * @interface Title11c67b72c9c610000edf72f0b3c5004f
 */
export interface Title11c67b72c9c610000edf72f0b3c5004f {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Title11c67b72c9c610000edf72f0b3c5004f
     */
    'descriptor'?: string;
}

