/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryPredefinedNameComponentAb5c028f50b310001b9916066f1f0250 } from './country-predefined-name-component-ab5c028f50b310001b9916066f1f0250';

/**
 * Returns the prefix from the name.
 * @export
 * @interface TitleE08d883b5eae10000403d7b62abb02e7
 */
export interface TitleE08d883b5eae10000403d7b62abb02e7 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof TitleE08d883b5eae10000403d7b62abb02e7
     */
    'descriptor'?: string;
}

