/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Transaction status or workflow state for an event. Example: Successfully Completed, Denied, Terminated
 * @export
 * @interface TransactionStatus7457adcbe0fa1000089b63ab3a510000
 */
export interface TransactionStatus7457adcbe0fa1000089b63ab3a510000 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof TransactionStatus7457adcbe0fa1000089b63ab3a510000
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof TransactionStatus7457adcbe0fa1000089b63ab3a510000
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof TransactionStatus7457adcbe0fa1000089b63ab3a510000
     */
    'href'?: string;
}

