/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InstantMessengerTypeE3f4243ada0b10000d441b1688d20087 } from './instant-messenger-type-e3f4243ada0b10000d441b1688d20087';

/**
 * Instant Messenger Type
 * @export
 * @interface TypeDe08a6c876a810000cb2e3dd8853001a
 */
export interface TypeDe08a6c876a810000cb2e3dd8853001a {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof TypeDe08a6c876a810000cb2e3dd8853001a
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof TypeDe08a6c876a810000cb2e3dd8853001a
     */
    'id'?: string;
}

