/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InstantMessengerTypeAb827579ee17100023fd6abda45c01b9 } from './instant-messenger-type-ab827579ee17100023fd6abda45c01b9';

/**
 * Instant Messenger Type
 * @export
 * @interface Type33e26848dc00100037bb584480fe014a
 */
export interface Type33e26848dc00100037bb584480fe014a {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Type33e26848dc00100037bb584480fe014a
     */
    'descriptor'?: string;
}

