/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MilitaryServiceType6de928ab128410005bc12d1bc69b0230 } from './military-service-type6de928ab128410005bc12d1bc69b0230';

/**
 * Military Service Type for Military Service
 * @export
 * @interface Type6de928ab128410005b41e4ac0ec5021d
 */
export interface Type6de928ab128410005b41e4ac0ec5021d {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Type6de928ab128410005b41e4ac0ec5021d
     */
    'descriptor'?: string;
}

