/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf
 */
export interface UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf {
    /**
     * Uniform Service Reserve Status Description.
     * @type {string}
     * @memberof UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf
     */
    'uniformServiceReserveStatusDescription'?: string;
    /**
     * Uniform Service Reserve Status Name.
     * @type {string}
     * @memberof UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf
     */
    'uniformServiceReserveStatusName'?: string;
    /**
     * Uniform Service Reserve Status Code
     * @type {string}
     * @memberof UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf
     */
    'uniformServiceReserveStatusCode'?: string;
    /**
     * The inactive flag.
     * @type {boolean}
     * @memberof UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf
     */
    'inactive'?: boolean;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof UniformServiceReserveStatusB26f12db214d10000bf4b358ee390000AllOf
     */
    'id'?: string;
}

