/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UniversalID814af6e5b9fa100022bff92eb5140117 } from './universal-id814af6e5b9fa100022bff92eb5140117';

/**
 * \\~Universal Id\\~ for the Person
 * @export
 * @interface UniversalIDE451ce2c8b48100007c31392a1ff00c2
 */
export interface UniversalIDE451ce2c8b48100007c31392a1ff00c2 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof UniversalIDE451ce2c8b48100007c31392a1ff00c2
     */
    'id'?: string;
}

