/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsageType6a6eaf50b6ad100012e8021249e601fcAllOf } from './usage-type6a6eaf50b6ad100012e8021249e601fc-all-of';

/**
 * 
 * @export
 * @interface UniversalID814af6e5b9fa100022bff92eb5140117
 */
export interface UniversalID814af6e5b9fa100022bff92eb5140117 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof UniversalID814af6e5b9fa100022bff92eb5140117
     */
    'id'?: string;
}

