/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns the primary Role of the person who uploaded the Attachment.
 * @export
 * @interface UploadedByB32ff437243510000e22e06470370160
 */
export interface UploadedByB32ff437243510000e22e06470370160 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof UploadedByB32ff437243510000e22e06470370160
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof UploadedByB32ff437243510000e22e06470370160
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof UploadedByB32ff437243510000e22e06470370160
     */
    'href'?: string;
}

