/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageBehavior1089da0ab90910000fa6c19789ce0896AllOf
 */
export interface UsageBehavior1089da0ab90910000fa6c19789ce0896AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof UsageBehavior1089da0ab90910000fa6c19789ce0896AllOf
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof UsageBehavior1089da0ab90910000fa6c19789ce0896AllOf
     */
    'id'?: string;
}

