/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContactUsageAb827579ee171000211397a6dede017d } from './contact-usage-ab827579ee171000211397a6dede017d';
import { UsageBehavior33e26848dc0010003a3c3827858901b4 } from './usage-behavior33e26848dc0010003a3c3827858901b4';
import { UsageType901718dd5e7910000cb06dace3950299 } from './usage-type901718dd5e7910000cb06dace3950299';

/**
 * Address Instance Referenced
 * @export
 * @interface UsageA58f621b14ee100014b01c034eeb00f3
 */
export interface UsageA58f621b14ee100014b01c034eeb00f3 {
    /**
     * True if the communication method has any  primary usage type.
     * @type {boolean}
     * @memberof UsageA58f621b14ee100014b01c034eeb00f3
     */
    'primary'?: boolean;
    /**
     * 
     * @type {UsageType901718dd5e7910000cb06dace3950299}
     * @memberof UsageA58f621b14ee100014b01c034eeb00f3
     */
    'usageType'?: UsageType901718dd5e7910000cb06dace3950299;
    /**
     * Usage behaviors for the communication method, such as mailing, billing shipping etc.
     * @type {Array<UsageBehavior33e26848dc0010003a3c3827858901b4>}
     * @memberof UsageA58f621b14ee100014b01c034eeb00f3
     */
    'usedFor'?: Array<UsageBehavior33e26848dc0010003a3c3827858901b4>;
    /**
     * True if the communication method is public. If no results are returned, the communication method is private.
     * @type {boolean}
     * @memberof UsageA58f621b14ee100014b01c034eeb00f3
     */
    'public'?: boolean;
}

