/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsageType901718dd5e7910000cc03935c73e029c } from './usage-type901718dd5e7910000cc03935c73e029c';

/**
 * Returns the usage type for a given communication method.
 * @export
 * @interface UsageType901718dd5e7910000cb06dace3950299
 */
export interface UsageType901718dd5e7910000cb06dace3950299 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof UsageType901718dd5e7910000cb06dace3950299
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof UsageType901718dd5e7910000cb06dace3950299
     */
    'descriptor'?: string;
}

