/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageType901718dd5e7910000cc03935c73e029cAllOf
 */
export interface UsageType901718dd5e7910000cc03935c73e029cAllOf {
    /**
     * Id of the instance
     * @type {string}
     * @memberof UsageType901718dd5e7910000cc03935c73e029cAllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof UsageType901718dd5e7910000cc03935c73e029cAllOf
     */
    'descriptor'?: string;
}

