/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsageBehavior33e26848dc0010003a3c3827858901b4 } from './usage-behavior33e26848dc0010003a3c3827858901b4';
import { UsageType81f66ab16f7510005c6076c4248b4875 } from './usage-type81f66ab16f7510005c6076c4248b4875';
import { WorkContactUsage81f66ab16f7510005c60769e6db24871 } from './work-contact-usage81f66ab16f7510005c60769e6db24871';

/**
 * Address Instance Referenced
 * @export
 * @interface UsageC1bb9f46f65210002d2fa2e7babe00a8
 */
export interface UsageC1bb9f46f65210002d2fa2e7babe00a8 {
    /**
     * Is Public Visibility
     * @type {boolean}
     * @memberof UsageC1bb9f46f65210002d2fa2e7babe00a8
     */
    'public'?: boolean;
    /**
     * Returns the description for a given communication method.
     * @type {string}
     * @memberof UsageC1bb9f46f65210002d2fa2e7babe00a8
     */
    'comment'?: string;
    /**
     * Used For
     * @type {Array<UsageBehavior33e26848dc0010003a3c3827858901b4>}
     * @memberof UsageC1bb9f46f65210002d2fa2e7babe00a8
     */
    'usedFor'?: Array<UsageBehavior33e26848dc0010003a3c3827858901b4>;
    /**
     * 
     * @type {UsageType81f66ab16f7510005c6076c4248b4875}
     * @memberof UsageC1bb9f46f65210002d2fa2e7babe00a8
     */
    'usageType'?: UsageType81f66ab16f7510005c6076c4248b4875;
    /**
     * Returns Boolean Value False
     * @type {boolean}
     * @memberof UsageC1bb9f46f65210002d2fa2e7babe00a8
     */
    'primary'?: boolean;
}

