/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsageBehavior33e26848dc0010003a3c3827858901b4AllOf } from './usage-behavior33e26848dc0010003a3c3827858901b4-all-of';

/**
 * 
 * @export
 * @interface UsageBehavior33e26848dc0010003a3c3827858901b4
 */
export interface UsageBehavior33e26848dc0010003a3c3827858901b4 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof UsageBehavior33e26848dc0010003a3c3827858901b4
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof UsageBehavior33e26848dc0010003a3c3827858901b4
     */
    'id'?: string;
}

