/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HomeContactUsageC1bb9f46f65210002d3c341a5dc400b8 } from './home-contact-usage-c1bb9f46f65210002d3c341a5dc400b8';
import { UsageBehavior33e26848dc0010003a3c3827858901b4 } from './usage-behavior33e26848dc0010003a3c3827858901b4';
import { UsageTypeC1bb9f46f65210002d3c343d773200bc } from './usage-type-c1bb9f46f65210002d3c343d773200bc';

/**
 * Address Instance Referenced
 * @export
 * @interface Usage81f66ab16f7510005c53d917926f4857
 */
export interface Usage81f66ab16f7510005c53d917926f4857 {
    /**
     * Returns the description for a given communication method.
     * @type {string}
     * @memberof Usage81f66ab16f7510005c53d917926f4857
     */
    'comment'?: string;
    /**
     * Is Public Visibility
     * @type {boolean}
     * @memberof Usage81f66ab16f7510005c53d917926f4857
     */
    'public'?: boolean;
    /**
     * Is Primary
     * @type {boolean}
     * @memberof Usage81f66ab16f7510005c53d917926f4857
     */
    'primary'?: boolean;
    /**
     * Used For
     * @type {Array<UsageBehavior33e26848dc0010003a3c3827858901b4>}
     * @memberof Usage81f66ab16f7510005c53d917926f4857
     */
    'usedFor'?: Array<UsageBehavior33e26848dc0010003a3c3827858901b4>;
    /**
     * 
     * @type {UsageTypeC1bb9f46f65210002d3c343d773200bc}
     * @memberof Usage81f66ab16f7510005c53d917926f4857
     */
    'usageType'?: UsageTypeC1bb9f46f65210002d3c343d773200bc;
}

