/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VeteransPreference898f4bc8578c100010cc072a1b140000AllOf } from './veterans-preference898f4bc8578c100010cc072a1b140000-all-of';

/**
 * 
 * @export
 * @interface VeteransPreference898f4bc8578c100010cc072a1b140000
 */
export interface VeteransPreference898f4bc8578c100010cc072a1b140000 {
    /**
     * \\~Veteran\'s Preference\\~ Category
     * @type {string}
     * @memberof VeteransPreference898f4bc8578c100010cc072a1b140000
     */
    'militaryServicePreferenceName'?: string;
    /**
     * Military Service Preference Code
     * @type {string}
     * @memberof VeteransPreference898f4bc8578c100010cc072a1b140000
     */
    'militaryServicePreferenceCode'?: string;
    /**
     * The Inactive flag.
     * @type {boolean}
     * @memberof VeteransPreference898f4bc8578c100010cc072a1b140000
     */
    'inactive'?: boolean;
    /**
     * Military Service Preference Description
     * @type {string}
     * @memberof VeteransPreference898f4bc8578c100010cc072a1b140000
     */
    'militaryServicePreferenceDescription'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof VeteransPreference898f4bc8578c100010cc072a1b140000
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof VeteransPreference898f4bc8578c100010cc072a1b140000
     */
    'id'?: string;
}

