/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommonBooleanRepresentationC6cfba790def100010efb5c8ebf00000 } from './common-boolean-representation-c6cfba790def100010efb5c8ebf00000';

/**
 * \\~Veteran\'s Preference for RIF\\~
 * @export
 * @interface VeteransPreferenceForRIFA04210f7e84510001fb2873228810000
 */
export interface VeteransPreferenceForRIFA04210f7e84510001fb2873228810000 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof VeteransPreferenceForRIFA04210f7e84510001fb2873228810000
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof VeteransPreferenceForRIFA04210f7e84510001fb2873228810000
     */
    'id'?: string;
}

