/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsageE357ae6d466510000ce25a08bfe401b3 } from './usage-e357ae6d466510000ce25a08bfe401b3';
import { WebAddressReferenceE357ae6d466510000ce259f323be01b0AllOf } from './web-address-reference-e357ae6d466510000ce259f323be01b0-all-of';

/**
 * 
 * @export
 * @interface WebAddressReferenceE357ae6d466510000ce259f323be01b0
 */
export interface WebAddressReferenceE357ae6d466510000ce259f323be01b0 {
    /**
     * 
     * @type {UsageE357ae6d466510000ce25a08bfe401b3}
     * @memberof WebAddressReferenceE357ae6d466510000ce259f323be01b0
     */
    'usage'?: UsageE357ae6d466510000ce25a08bfe401b3;
    /**
     * The complete URL address for the web address.
     * @type {string}
     * @memberof WebAddressReferenceE357ae6d466510000ce259f323be01b0
     */
    'url'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof WebAddressReferenceE357ae6d466510000ce259f323be01b0
     */
    'id'?: string;
}

