/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095 } from './work-address-reference-c1bb9f46f65210002d2fa259a1c10095';

/**
 * 
 * @export
 * @interface WorkContactInformationChangesGetAddressesStagedResponse
 */
export interface WorkContactInformationChangesGetAddressesStagedResponse {
    /**
     * 
     * @type {Array<WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095>}
     * @memberof WorkContactInformationChangesGetAddressesStagedResponse
     */
    'data'?: Array<WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095>;
    /**
     * 
     * @type {number}
     * @memberof WorkContactInformationChangesGetAddressesStagedResponse
     */
    'total'?: number;
}

