/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebAddressReferenceE357ae6d466510000ce259f323be01b0 } from './web-address-reference-e357ae6d466510000ce259f323be01b0';

/**
 * 
 * @export
 * @interface WorkContactInformationChangesGetWebAddressesStagedResponse
 */
export interface WorkContactInformationChangesGetWebAddressesStagedResponse {
    /**
     * 
     * @type {Array<WebAddressReferenceE357ae6d466510000ce259f323be01b0>}
     * @memberof WorkContactInformationChangesGetWebAddressesStagedResponse
     */
    'data'?: Array<WebAddressReferenceE357ae6d466510000ce259f323be01b0>;
    /**
     * 
     * @type {number}
     * @memberof WorkContactInformationChangesGetWebAddressesStagedResponse
     */
    'total'?: number;
}

