/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryC1bb9f46f65210002d2fa329fe6700b4 } from './country-c1bb9f46f65210002d2fa329fe6700b4';
import { CountryCityC1bb9f46f65210002d2fa2bb24a300a1 } from './country-city-c1bb9f46f65210002d2fa2bb24a300a1';
import { CountryRegionC1bb9f46f65210002d2fa322479a00b2 } from './country-region-c1bb9f46f65210002d2fa322479a00b2';
import { UsageC1bb9f46f65210002d2fa2e7babe00a8 } from './usage-c1bb9f46f65210002d2fa2e7babe00a8';
import { WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095AllOf } from './work-address-reference-c1bb9f46f65210002d2fa259a1c10095-all-of';

/**
 * 
 * @export
 * @interface WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
 */
export interface WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095 {
    /**
     * Address Line 3
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine3'?: string;
    /**
     * Local Address Line 8
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine8Local'?: string;
    /**
     * Region Subdivision 2
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'regionSubdivision2'?: string;
    /**
     * City - Local
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'cityLocal'?: string;
    /**
     * City Subdivision 1 - Local
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'citySubdivision1Local'?: string;
    /**
     * Local Address Line 6
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine6Local'?: string;
    /**
     * Local Address Line 4
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine4Local'?: string;
    /**
     * Region Subdivision 1 - Local
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'regionSubdivision1Local'?: string;
    /**
     * 
     * @type {CountryC1bb9f46f65210002d2fa329fe6700b4}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'country'?: CountryC1bb9f46f65210002d2fa329fe6700b4;
    /**
     * Address Line 9
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine9'?: string;
    /**
     * Address Line 4
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine4'?: string;
    /**
     * City Subdivision 1
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'citySubdivision1'?: string;
    /**
     * Address Line 8
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine8'?: string;
    /**
     * Address Line 1
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine1'?: string;
    /**
     * Local Address Line 5
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine5Local'?: string;
    /**
     * Address Line 6
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine6'?: string;
    /**
     * City
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'city'?: string;
    /**
     * Local Address Line 3
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine3Local'?: string;
    /**
     * Postal Code
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'postalCode'?: string;
    /**
     * Local Address Line 9
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine9Local'?: string;
    /**
     * Address Line 2
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine2'?: string;
    /**
     * Local Address Line 1
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine1Local'?: string;
    /**
     * Local Address Line 7
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine7Local'?: string;
    /**
     * 
     * @type {CountryRegionC1bb9f46f65210002d2fa322479a00b2}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'countryRegion'?: CountryRegionC1bb9f46f65210002d2fa322479a00b2;
    /**
     * Address Line 5
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine5'?: string;
    /**
     * 
     * @type {UsageC1bb9f46f65210002d2fa2e7babe00a8}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'usage'?: UsageC1bb9f46f65210002d2fa2e7babe00a8;
    /**
     * Region Subdivision 1
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'regionSubdivision1'?: string;
    /**
     * Address Line 7
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine7'?: string;
    /**
     * The date this business process takes effect.
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'effective'?: string;
    /**
     * City Subdivision 2 - Local
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'citySubdivision2Local'?: string;
    /**
     * Local Address Line 2
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'addressLine2Local'?: string;
    /**
     * 
     * @type {CountryCityC1bb9f46f65210002d2fa2bb24a300a1}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'countryCity'?: CountryCityC1bb9f46f65210002d2fa2bb24a300a1;
    /**
     * City Subdivision 2
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'citySubdivision2'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof WorkAddressReferenceC1bb9f46f65210002d2fa259a1c10095
     */
    'id'?: string;
}

