/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AlternateWorkLocationD72a8353f91e1000169a83b894e7046e } from './alternate-work-location-d72a8353f91e1000169a83b894e7046e';
import { WorkContactChangeEventD72a8353f91e1000169a839c31a0046dAllOf } from './work-contact-change-event-d72a8353f91e1000169a839c31a0046d-all-of';

/**
 * 
 * @export
 * @interface WorkContactChangeEventD72a8353f91e1000169a839c31a0046d
 */
export interface WorkContactChangeEventD72a8353f91e1000169a839c31a0046d {
    /**
     * 
     * @type {AlternateWorkLocationD72a8353f91e1000169a83b894e7046e}
     * @memberof WorkContactChangeEventD72a8353f91e1000169a839c31a0046d
     */
    'alternateWorkLocation'?: AlternateWorkLocationD72a8353f91e1000169a83b894e7046e;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof WorkContactChangeEventD72a8353f91e1000169a839c31a0046d
     */
    'descriptor'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof WorkContactChangeEventD72a8353f91e1000169a839c31a0046d
     */
    'id'?: string;
}

