/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016 } from './instant-messenger-reference-de08a6c876a810000cb2e38a1d2a0016';

/**
 * 
 * @export
 * @interface WorkContactInformationChangesGetStagedInstantMessengersResponse
 */
export interface WorkContactInformationChangesGetStagedInstantMessengersResponse {
    /**
     * 
     * @type {Array<InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016>}
     * @memberof WorkContactInformationChangesGetStagedInstantMessengersResponse
     */
    'data'?: Array<InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016>;
    /**
     * 
     * @type {number}
     * @memberof WorkContactInformationChangesGetStagedInstantMessengersResponse
     */
    'total'?: number;
}

