/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkerDocument15d8b82e323110000e0117c92d9803b2AllOf } from './worker-document15d8b82e323110000e0117c92d9803b2-all-of';

/**
 * 
 * @export
 * @interface WorkerDocument15d8b82e323110000e0117c92d9803b2
 */
export interface WorkerDocument15d8b82e323110000e0117c92d9803b2 {
    /**
     * The additional comments associated with the Worker Document.
     * @type {string}
     * @memberof WorkerDocument15d8b82e323110000e0117c92d9803b2
     */
    'comment'?: string;
    /**
     * The filename of the Worker Document.
     * @type {string}
     * @memberof WorkerDocument15d8b82e323110000e0117c92d9803b2
     */
    'fileName'?: string;
}

