/*
person

The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.

The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsageBehavior33e26848dc0010003a3c3827858901b4 } from './usage-behavior33e26848dc0010003a3c3827858901b4';
import { UsageType81f66ab16f7510005c6076c4248b4875 } from './usage-type81f66ab16f7510005c6076c4248b4875';

/**
 * 
 * @export
 * @interface WorkContactUsage81f66ab16f7510005c60769e6db24871AllOf
 */
export interface WorkContactUsage81f66ab16f7510005c60769e6db24871AllOf {
    /**
     * Is Public Visibility
     * @type {boolean}
     * @memberof WorkContactUsage81f66ab16f7510005c60769e6db24871AllOf
     */
    'public'?: boolean;
    /**
     * Returns the description for a given communication method.
     * @type {string}
     * @memberof WorkContactUsage81f66ab16f7510005c60769e6db24871AllOf
     */
    'comment'?: string;
    /**
     * Used For
     * @type {Array<UsageBehavior33e26848dc0010003a3c3827858901b4>}
     * @memberof WorkContactUsage81f66ab16f7510005c60769e6db24871AllOf
     */
    'usedFor'?: Array<UsageBehavior33e26848dc0010003a3c3827858901b4>;
    /**
     * 
     * @type {UsageType81f66ab16f7510005c6076c4248b4875}
     * @memberof WorkContactUsage81f66ab16f7510005c60769e6db24871AllOf
     */
    'usageType'?: UsageType81f66ab16f7510005c6076c4248b4875;
    /**
     * Returns Boolean Value False
     * @type {boolean}
     * @memberof WorkContactUsage81f66ab16f7510005c60769e6db24871AllOf
     */
    'primary'?: boolean;
}

